### ISSUE TITLE
cannot install in lightsail ubuntu instance with magento installed

### ISSUE THREAD

**Issue by michhy** [develodesign/m2-paypal-payment#11]
Hello, 

I tried to run the two lines of codes, but not sure if the module has been installed, as I cannot find the develodesign/m2-paypal-payment in vendor folder.
I run the code in magento folder.

Please see the attached screenshot:
![螢幕截圖 2019-04-24 下午7 45 07](https://user-images.githubusercontent.com/37435427/56657101-c6b94100-66c9-11e9-9cd2-f2cc5636eeea.png)

Thanks in advance.

**Comment by michhy** [comment]
Hi sorry it is activated after upgrade and deploy magento.

Thank you.

**Comment by dimasch** [comment]
Thanks, @michhy 

Yes, need enable via `bin/magento module:enable --all`

I will update README.
