### ISSUE TITLE
error: API call failed: The requested Payment Method is not available.

### ISSUE THREAD

**Issue by dimasch** [develodesign/m2-paypal-payment#7]
\+ @collymore 
![order](https://user-images.githubusercontent.com/414067/47675160-9721f400-dbd2-11e8-9fc4-0456ce335771.png)

**Comment by dimasch** [comment]
This task in progress.

**Comment by dimasch** [comment]
Resolved by https://github.com/develodesign/m2-paypal-payment/commit/31f91d7e7a2ecfe30a6e136453e09e0fcda49267

**Comment by kovaljames** [comment]
I'm facing the same issue in Magento ver. 2.3.1.

![Captura de tela de 2019-04-16 13-52-12](https://user-images.githubusercontent.com/7256211/56229019-5cf8c180-604f-11e9-9f52-66f39b934b05.png)
